version: '3'

services:
  books:
    build: ./BooksService
    container_name: books-service
    restart: always
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "5001:8090"
    expose:
      - 8090
    depends_on:
      - mongo

  mongo:
    image: mongo
    contaivner_name: mongo-service
    ports:
      - "27017:27017"