name: Build, Test, and Query
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_COURSE_USERNAME }}
          password: ${{ secrets.DOCKER_COURSE_PASSWORD }}
      - name: Set DATE
        run: echo "DATE=$(date -I)" >> $GITHUB_ENV
      - name: Build the Docker image
        run: |
          docker build . --file ./BooksService/Dockerfile --tag ${{ secrets.DOCKER_COURSE_USERNAME }}/booksvr-v2
          docker tag ${{ secrets.DOCKER_COURSE_USERNAME }}/booksvr-v2 ${{ secrets.DOCKER_COURSE_USERNAME }}/booksvr-v2:${{ env.DATE }}
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_COURSE_USERNAME }}/booksvr-v2
          docker push ${{ secrets.DOCKER_COURSE_USERNAME }}/booksvr-v2:${{ env.DATE }}
      - name: Creating log file
        run: |
          echo "$(date -Iminutes)" > log.txt
          echo "Yogev Cuperman" >> log.txt
      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: workflow-log
          path: log.txt
